### ISSUE TITLE
Broken due to required partition key change in Cosmos DB

### ISSUE THREAD

**Issue by crpietschmann** [CosmosDB/labs#20]
The Technical Deep Dive lab is broken due to recent changes in Cosmos DB where all Collections are now required to have a Partition Key.

https://cosmosdb.github.io/labs/technical_deep_dive/05-troubleshooting_failed_requests.html

**Comment by timsander1** [comment]
We have moved to new labs using our V3 .NET sdk so I am closing this issue. This issue is addressed there.
