### ISSUE TITLE
Benchmarks in lab 02 failed with ServiceNotAvailableException

### ISSUE THREAD

**Issue by SamuelWr** [CosmosDB/labs#22]
in https://github.com/CosmosDB/labs/blob/master/technical_deep_dive/02-creating_multi_partition_solution.md
The benchmark app failed to open the client with a Microsoft.Azure.Documents.ServiceUnavailableException
Removing the ConnectionPolicy fixed the problem

**Comment by seesharprun** [comment]
The challenge will be to figure out how to solve this without removing the ability to specify a region.

In the 2.x SDK, you specify the preferred locations using thr policy: https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-global-distribution-sql-api#connecting-to-a-preferred-region-using-the-sql-api

Maybe this is a good excuse to move to v3 of the SDK.

**Comment by timsander1** [comment]
We have moved to new labs using our V3 .NET sdk so closing this issue
