### ISSUE TITLE
JDK/JRE download location in Java Labs

### ISSUE THREAD

**Issue by anishi1222** [CosmosDB/labs#27]
In [Java Labs](https://cosmosdb.github.io/labs/#java-labs), download links of Java 8 (or greater) JDK and JRE are pointed to Java Download page in OTN (Oracle Technology Network).

- JDK 8
 [https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- JRE 8
 [https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)

According to [Oracle Technology Network License Agreement for Oracle Java SE](https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html), indeed downloading JDK/JRE from this page and using them are valid in case of personal study purpose.
But I'm wondering if download link to [http://jdk.java.net/](http://jdk.java.net/) or Azul is better. Furthermore, as Java 8 is out of public update, I'm afraid that Microsoft should recommend using the latest non-LTS or LTS JDK/JRE.

**Comment by TheovanKraay** [comment]
The lab recommends Java 8 "or later". The primary reason for baselining at Java 8 was that, although the code was tested at Java 11, as stated in the lab notes, some of the open source tools used in the labs do not compile at versions beyond Java 8. In addition, although Java 8 is out of public update, it will continue to receive premier support until March 2022. As such, there are many, many Enterprises still using Java 8, and they will continue to do so for some time.

**Comment by anishi1222** [comment]
Thanks for your comment and sorry for my late response.
Ideally every developer using Java 8 should make a support contract with some JDK vendor, but the number of developer and company which do so would be quite a few...
Anyway, I understood intention of this content.
