### ISSUE TITLE
Lab 4: transaction blob object not available

### ISSUE THREAD

**Issue by falloutxAY** [CosmosDB/labs#31]
lab 4: Troubleshooting and Tuning Azure Cosmos DB Requests, Task 3 Import Lab Data Into Collection.

The **Transaction** blob object is not there. Error in ADF 
The required Blob is missing. ContainerName: 

> https://cosmoslabs.blob.core.windows.net/transactions, ContainerExist: True, BlobPrefix: , BlobCount: 0.. Activity ID:ce038f6f-4d23-4e14-a25a-3f6ac1592e5c

**Comment by timsander1** [comment]
I re-added this. The required transactions.json file is now available in the correct location.
