### ISSUE TITLE
LangVersion in .NET Core projects

### ISSUE THREAD

**Issue by seesharprun** [CosmosDB/labs#33]
When .NET Core 3 is generally available, you should be able to update the .NET labs to remove the step where you set the ``LangVersion`` property in the project configuration file. That was required since the asynchronous Main feature came after the release of .NET Core 2.

**Comment by timsander1** [comment]
got it. Thanks Sydney!

**Comment by seesharprun** [comment]
I am reopening this issue to bring up that .NET Core 3.1 is the new long-term release and the lab instructions should be updated to reflect this in two places:

- The ``langVersion`` parameter should be removed
- The readme should tell people to download .NET Core 3.1 instead.

I would be happy to PR these changes, any issue with that?

**Comment by timsander1** [comment]
Sure. That would be great. Thank you for offering!

**Comment by timsander1** [comment]
Closing this issue. We are migrating to the new repo here: https://github.com/AzureCosmosDB/labs

Please feel free to recreate the issue there.
