### ISSUE TITLE
Unable to access blob storage lab - Lab 2

### ISSUE THREAD

**Issue by falloutxAY** [CosmosDB/labs#35]
Lab 2, Exercise 1 : Task 3, Step 12.

Unable to get the json.

**Comment by timsander1** [comment]
I just tested Lab 2 and was able to import the data into Cosmos DB from the blob storage link. Does the ADF job fail or are you unable to access the json file from blob storage link altogether?

**Comment by timsander1** [comment]
Closing this issue. Let me know if you have any additional questions.
