### ISSUE TITLE
Update Instruction to include registration of CosmosDB

### ISSUE THREAD

**Issue by ChubaOraka** [CosmosDB/labs#48]
I kept getting errors running `.\labSetup.ps1` on no. 6 of the [setup instructions](https://github.com/CosmosDB/labs/blob/master/dotnet/labs/00-account_setup.md). At the top of the stacktrace was this:

`New-AzResource : MissingSubscriptionRegistration : The subscription is not registered to use namespace
'Microsoft.DocumentDB'. See https://aka.ms/rps-not-found for how to register subscriptions.
At ...`

So I'll suggest the [setup instructions](https://github.com/CosmosDB/labs/blob/master/dotnet/labs/00-account_setup.md) should be updated with a suggestion to register CosmosDB:

`Register-AzResourceProvider -ProviderNamespace Microsoft.DocumentDB`

**Comment by timsander1** [comment]
Hi @ChubaOraka , thanks for pointing this out. I think this could happen for the creation of many Azure services (not specific to Cosmos DB). We will add a note to clarify though. Thanks!
