### ISSUE TITLE
Probably a little typo in the Indexing Policy JSON

### ISSUE THREAD

**Issue by ChubaOraka** [CosmosDB/labs#49]
Though the last composite index query worked (i.e. `SELECT * FROM c ORDER BY c.foodGroup DESC, c.manufacturerName ASC`), I suspect the last key-value pair at the ent of the [Adding a Composite Index](https://github.com/CosmosDB/labs/blob/master/dotnet/labs/04-indexing_in_cosmosdb.md#adding-a-composite-index) section should be `"order": "descending"`.

For clarity, the JSON for the indexing policy configuration should be:

```JSON
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/manufacturerName/*"
        },
        {
            "path": "/foodGroup/*"
        }
    ],
    "excludedPaths": [
        {
            "path": "/*"
        },
        {
            "path": "/\"_etag\"/?"
        }
    ],
    "compositeIndexes": [
        [
            {
                "path": "/foodGroup",
                "order": "ascending"
            },
            {
                "path": "/manufacturerName",
                "order": "ascending"
            }
        ],
        [
            {
                "path": "/foodGroup",
                "order": "descending"
            },
            {
                "path": "/manufacturerName",
                "order": "descending"
            }
        ]
    ]
}

```

**Comment by timsander1** [comment]
Hi @ChubaOraka , this is actually not a typo but I agree that it is unclear. I added in a note to clarify.

When you define the order for properties in a composite index, they must either exactly match the order in the ORDER BY clause or be, in all cases, the opposite value.

So in this case, the composite index on (foodGroup ASC, manufacturerName ASC) will also support an ORDER BY query where the order is descending on each of these properties.
