### ISSUE TITLE
Lab-08 PartitionKey error

### ISSUE THREAD

**Issue by danielkon96** [CosmosDB/labs#54]
Unhandled Exception: Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: 400 Substatus: 1001 Reason: (Microsoft.Azure.Documents.BadRequestException: Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]}

No matter what approach I take, no matter how much I research, I still am getting this error. I updated to the latest nuget package for CosmosDB, still getting this error.

I cannot continue the lab without this step.

**Comment by danielkon96** [comment]
I actually found a fix that would be nice to add to the documentation for lab-08.

Under the AddItem function in Program.cs in the DataGenerator folder, replace (new PartitionKey(item.Item) on line 46 with null.

**Comment by danielkon96** [comment]
Ok, so the fix is when you are creating a container in the portal, make sure the key is set to /Item.

You will need to create the database and the container manually.

**Comment by MathewsThankachan** [comment]
Hi Daniel, 

Unfortunately that didnt work for me. Do you have any other solution.

If I dont pass the partionkey to the CreateItemAsync method. It works. But I wanted to make work with passing Partitionkey

Matt

**Comment by MathewsThankachan** [comment]
One more thing, I get only the exception reason code as "**Response status code does not indicate success: 400 Substatus: 1001 Reason: ().**"

**Comment by danielkon96** [comment]
Hey Mathews,

Is your reason blank in the error code?

You might need to do /YourPartitionKeyNameHere.

If that doesn't work, do you have a snippet of code?

**Comment by MathewsThankachan** [comment]
Thanks Daniel for reaching out. I figured out the weird scenario.  my partition key was defined as  /PostCode which throws error while the Partition key /Postcode works. Not sure why MS is so particular abt case. 

Note : On container it was defined as /Postcode
