### ISSUE TITLE
Setup of Cosmos Containers can be prohibitively expensive

### ISSUE THREAD

**Issue by jojackso** [CosmosDB/labs#55]
In the pre-lab setup, the PowerShell script provisions >22k RUs.  This has a cost of ~$1.80/hr.  Provisioned RUs should be revised or instructions at least warning of this cost potential.

**Comment by timsander1** [comment]
Hi @jojackso , I can add a note to the pre-lab section. We need to keep the throughput high to quickly import data into existing collections for the lab. You are welcome to lower this provisioned throughput amount after the initial data load has completed. I will add a note about this.
