### ISSUE TITLE
Incorrect text in Module 2

### ISSUE THREAD

**Issue by devjourney** [CosmosDB/labs#7]
In technical_deep_dive/02-creating_multi_partition_solution.md the phrase in part III that says "Observe the code in the ExecuteLogic method." seems misplaced.

**Comment by seesharprun** [comment]
This was resolved as part of commit 3f49d8af44468ff7640cd3e382d13ba4c0299249

**Comment by seesharprun** [comment]
Turns out the **ExecuteLogic** method should have been called the **Main** method. Thanks for pointing this out!
