### ISSUE TITLE
IndexOf method not found

### ISSUE THREAD

**Issue by devjourney** [CosmosDB/labs#8]
In technical_deep_dive/02-creating_multi_partition_solution.md, when iterating over the foodInteractions, there's a reference to foodInteractions.**IndexOf(interaction)**. With the included references, this won't compile. It may be a reference to Infer.NET or some other set of extensions methods on IEnumerable. However, when I look in the solution file in this repo, I see that the reference to the IndexOf method was removed altogether. Seems like the documented code should build and match the solution file.

**Comment by seesharprun** [comment]
I just tested this out without an issue.

Do you have a reference to ``System.Linq`` at the top of your class file?

**Comment by devjourney** [comment]
Yes. Did this on my Mac and a PC. I copied code directly from the solution here to be sure. The solution in GitHub has no reference to IndexOf. Here's line 77 from the solution:

> await Console.Out.WriteLineAsync($"Document Created\t{result.Resource.Id}");

And it compiles just fine. When I swap in the code shown in the lab under Task II item 9:

> await Console.Out.WriteLineAsync($"Document #{foodInteractions.IndexOf(interaction):000} Created\t{result.Resource.Id}");

I definitely have all the right declarations, including System.Linq. Are you sure this extension method is available in one of the standard libraries? Also, why would you even use an IndexOf type implementation at all? Seems it would need to iterate and compare references which would be highly inefficient. I'd have incremented a local index variable and kept track of the offset myself for display.

**Comment by timsander1** [comment]
We have moved to new labs using our V3 .NET sdk so I am closing this issue.
